language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
      env: QA=yes
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer selfupdate
  - composer install
  - if [ "$QA" == "yes" ]; then composer global require --update-no-dev codeclimate/php-test-reporter:dev-master satooshi/php-coveralls:^1.0; fi
  - export PATH=$PATH:`composer global config bin-dir --absolute`

before_script:
  - |
    if [ "$QA" == "yes" ]; then
      curl -L -o runkit.tgz https://github.com/runkit7/runkit7/releases/download/1.0.7/runkit-1.0.7.tgz
      pecl install ./runkit.tgz
    fi

script:
  - composer travis

after_success:
  - |
    if [ "$QA" == "yes" ]; then
      travis_retry coveralls -v
      travis_retry test-reporter
    fi

addons:
  code_climate:
    repo_token: f7cda3c831806b53c3a4c7ba6a7585da152bef2bd29ac53bf512cea748d5ea40
